### PR TITLE
add country geoip lookup for endpoint addresses

### PR DESCRIPTION
**Pull request by furmur**
* add CLI option 'geoip_path' to specify Country MMDB path
* add attribute 'endpoint_country' to the 'wireguard_peer_endpoint' metric if 'geoip_path' was specified

### CODE REVIEW

**Comment by kbknapp** [comment]
Very cool idea but two general comments:

- I wonder what the performance cost is of doing lookups on every update tick; perhaps there is a way to amortize that or cache IPs that have already been looked up? Although I haven't tested or looked at it, my worry would be looking up the same peers over and over when their IP hasn't changed and thus the country wouldn't either.
- It'd probably be better to store the `maxminddb_reader` inside `Metrics` instead of having to re-pass the reader to `Metrics::update` over and over.

**Comment by kbknapp** [comment]
Also looks like this PR bumps the MSRV to 1.58.1 which is fine, but we need to set that new value in CI.

**Comment by furmur** [comment]
thank you for reviewing. fixed issues you mentioned.

strace for `./wireguard_exporter -p8080 -l127.0.0.1 -g/opt/geoip/GeoLite2-Country.mmdb`: 
```
openat(AT_FDCWD, "/opt/geoip/GeoLite2-Country.mmdb", O_RDONLY|O_CLOEXEC) = 9
statx(9, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=5652356, ...}) = 0
mmap(NULL, 5652480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fdc4abdc000
read(9, "\0\0\1\16\30(\0\0\2\16\0301\0\0\3\5\3723\0\0\4\16\0301\0\0\5\5\372\26\0\0"..., 5652356) = 5652356
read(9, "", 32)                         = 0
close(9)
```
`maxminddb` crate loads the whole database into the memory and then all lookups are performed within the memory over the [binary search tree](https://maxmind.github.io/MaxMind-DB/). so no performance issues here and caching would be excessive, but i can rewrite to use cache if you consider it is necessary.

**Comment by kbknapp** [comment]
Ah ok, good to know. It's *possible* that if we're looking at the same several IPs over-and-over some kind of caching layer would be a better long term approach as the caching layer, even naively implemented as a linear search would be `O(n)` versus the `maxminddb` `O(log n)`, however the in this case I think the actual values of `n` matter and a linear search over ~100 items will absolutely beat a binary search just due to how good CPUs are going through linear items in low cache levels.

However, I think that extra complication is fine to do without at least until we have some actual numbers and know if it'd be worth it or not.

I'm good with this merge, and I really appreciate your taking the time to put this together. I'll get a new version released hopefully tonight but feel free to ping me if you don't see one in the next few days.

**Comment by dmitry-sinina** [comment]
@kbknapp Could you release new version with this feature?

**Comment by kbknapp** [comment]
@dmitry-sinina thanks for the ping - v0.3.0 is out now on both crates.io and this project's release page.

**Pull request merged**
